## Papraphraser

In [34]:
from datasets import load_dataset

paraphraser = load_dataset("merionum/ru_paraphraser")
paraphraser

DatasetDict({
    train: Dataset({
        features: ['id', 'id_1', 'id_2', 'text_1', 'text_2', 'class'],
        num_rows: 7227
    })
    test: Dataset({
        features: ['id', 'id_1', 'id_2', 'text_1', 'text_2', 'class'],
        num_rows: 1924
    })
})

In [35]:
paraphraser_train = paraphraser["train"].to_pandas()

paraphraser_test = paraphraser["test"].to_pandas()

In [36]:
paraphraser_train.head()

,id,id_1,id_2,text_1,text_2,class
0,1,201,8159,Полицейским разрешат стрелять на поражение по ...,Полиции могут разрешить стрелять по хулиганам ...,0
1,2,202,8158,Право полицейских на проникновение в жилище ре...,Правила внесудебного проникновения полицейских...,0
2,3,273,8167,Президент Египта ввел чрезвычайное положение в...,Власти Египта угрожают ввести в стране чрезвыч...,0
3,4,220,8160,Вернувшихся из Сирии россиян волнует вопрос тр...,Самолеты МЧС вывезут россиян из разрушенной Си...,-1
4,5,223,8160,В Москву из Сирии вернулись 2 самолета МЧС с р...,Самолеты МЧС вывезут россиян из разрушенной Си...,0

In [37]:
paraphraser_train["class"].value_counts().sort_index()

class
-1    2582
0     2957
1     1688
Name: count, dtype: int64

In [55]:
paraphraser_train_bin = paraphraser_train[
    paraphraser_train["class"].isin(['-1', '1'])
].copy()

paraphraser_train_bin = paraphraser_train_bin[
    ["text_1", "text_2", "class"]
].rename(columns={
    "text_1": "sentence1",
    "text_2": "sentence2",
    "class": "label"
})

paraphraser_train_bin["label"] = paraphraser_train_bin["label"].astype(int)
paraphraser_train_bin["label"] = paraphraser_train_bin["label"].map({

    -1: 0,
    1: 1

})

In [56]:
paraphraser_train_bin["label"].value_counts()

label
0    2582
1    1688
Name: count, dtype: int64

In [53]:
paraphraser_test_bin = paraphraser_test[
    paraphraser_test["class"].isin(['-1', '1'])
].copy()

paraphraser_test_bin = paraphraser_test_bin[
    ["text_1", "text_2", "class"]
].rename(columns={
    "text_1": "sentence1",
    "text_2": "sentence2",
    "class": "label"
})

paraphraser_test_bin["label"] = paraphraser_test_bin["label"].astype(int)
paraphraser_test_bin["label"] = paraphraser_test_bin["label"].map({

    -1: 0,
    1: 1

})

In [54]:
paraphraser_test_bin["label"].value_counts()

label
0    772
1    374
Name: count, dtype: int64

## RuPaws

In [2]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path("../data")
RUPAWS_DIR = DATA_DIR / "rupaws_dataset"

In [3]:
qqp_train = pd.read_csv(
    RUPAWS_DIR / "train/rupaws_qqp_train.csv",
    sep=";"
)

wiki_train = pd.read_csv(
    RUPAWS_DIR / "train/rupaws_wiki_train.csv",
    sep=";"
)

qqp_train.head()

,sentence1,sentence2,label
0,"Почему же такие богатые мусульманские страны, ...","Почему богатые мусульманские страны, такие как...",1
1,Что представляет собой государственно-частное ...,Что представляет собой государственно-частное ...,1
2,В чем различия между объектно-ориентированным ...,В чем различия между объектно-ориентированным ...,1
3,"Являются ли современные языки (т.е. латынь, др...","Являются ли древние языки (т.е. латынь, древне...",0
4,"Если вы можете любить кого-то, но не любить их...","Если вы можете любить кого-то, но не любить их...",1

In [4]:
wiki_train.head()

,Unnamed: 0,sentence1,sentence2,label
0,1872,От автобусной остановки автобусы следуют до го...,"Автобусы идут от автовокзала в Бейлдон, Брэфсб...",0
1,308,"Стюартстоун расположен на севере, Диксвилль на...","К северу находится Стюартстоун, к востоку - Ко...",0
2,2434,"Он играл за клуб ""Kansas City Royals"" в течени...",Он сыграл за Chicago Cubs в течение десяти мат...,0
3,1290,"""Энкор"" слился с ""Сибирскими авиалиниями"" в 20...","В 2001 году авиакомпания ""Сибирь"" объединилась...",0
4,3159,В апреле 2014 президент Кеннет Свендсен ушел в...,Президент Кеннет Свендсен ушел в отставку в ап...,1

In [5]:
wiki_train = wiki_train[["sentence1", "sentence2", "label"]]

In [6]:
rupaws_train = pd.concat(
    [qqp_train, wiki_train],
    ignore_index=True
)

rupaws_train.shape

(7596, 3)

In [7]:
qqp_test = pd.read_csv(
    RUPAWS_DIR / "test/rupaws_qqp_test.csv",
    sep=";"
)

wiki_test = pd.read_csv(
    RUPAWS_DIR / "test/rupaws_wiki_test.csv",
    sep=";"
)

In [8]:
qqp_test.head()

,sentence1,sentence2,label
0,Каковы были основные эффекты землетрясения Кам...,Каковы были основные последствия землетрясения...,0
1,Как сделать мой новый номер телефона в качеств...,Как я сделаю свой старый телефон администратор...,0
2,Почему страны не могут себе позволить продукци...,"Почему страны, не позволяющие себе высококачес...",1
3,Нравятся ли мексиканским женщинам мужчины из В...,Нравятся ли женщинам Восточной Азии мексиканск...,0
4,Какие правила вождения в Джорджии против Мисси...,Каковы правила вождения в штате Миссисипи прот...,1

In [9]:
wiki_test.head()

,Unnamed: 0,sentence1,sentence2,label
0,2266,Добро пожаловать в мою гостиную была отснята в...,"Фильм ""Добро пожаловать в мою гостиную"" был сн...",1
1,2431,Поттер женился в 1945 г. У него и его жены Энн...,У него и его жены Мэри (носильщицы) было двое ...,0
2,2613,"В 1960 году Ардли женился на Бриджит Гантли, у...","В 1960 г. Ардли женился на Вивиане Вильсон, и ...",0
3,567,"Альбом был записан в шести различных сеансах, ...",Альбом был записан в шести различных сеансах н...,1
4,2172,Хаптика - это изучение прикосновения как невер...,Хаптики - это изучение прикосновения как хапти...,0

In [10]:
wiki_test = wiki_test[["sentence1", "sentence2", "label"]]

In [11]:
rupaws_test = pd.concat(
    [qqp_test, wiki_test],
    ignore_index=True
)

rupaws_test.shape

(1673, 3)

In [12]:
rupaws_train["label"].value_counts().sort_index()

label
0    4638
1    2958
Name: count, dtype: int64

In [13]:
rupaws_test["label"].value_counts().sort_index()

label
0    1024
1     649
Name: count, dtype: int64

In [14]:
print("QQP")
print(qqp_test["label"].value_counts().sort_index())

print("\nWIKI")
print(wiki_test["label"].value_counts().sort_index())

QQP
label
0    135
1    115
Name: count, dtype: int64

WIKI
label
0    889
1    534
Name: count, dtype: int64

In [57]:
train_full = pd.concat(
    [
        paraphraser_train_bin,
        rupaws_train[["sentence1", "sentence2", "label"]]
    ],
    ignore_index=True
)

In [59]:
print(train_full.shape)
print(train_full["label"].value_counts())
print(train_full["label"].value_counts(normalize=True))

(11866, 3)
label
0    7220
1    4646
Name: count, dtype: int64
label
0    0.608461
1    0.391539
Name: proportion, dtype: float64

In [60]:
train_full[["sentence1", "sentence2", "label"]].isna().sum()

sentence1    0
sentence2    0
label        0
dtype: int64

In [64]:
print("Полные дубликаты:", train_full.duplicated().sum())

print(
    "Дубликаты пар:",
    train_full[["sentence1", "sentence2"]].duplicated().sum()
)

Полные дубликаты: 0
Дубликаты пар: 0

In [63]:
train_full = train_full.drop_duplicates(
    subset=["sentence1", "sentence2"]
).reset_index(drop=True)

print(train_full.shape)

(11803, 3)

In [65]:
pairs = train_full[["sentence1", "sentence2"]].astype(str)

reverse_pairs = pd.DataFrame({
    "sentence1": pairs["sentence2"],
    "sentence2": pairs["sentence1"]
})

print(
    "Обратных пар:",
    train_full[["sentence1", "sentence2"]].merge(
        reverse_pairs,
        on=["sentence1", "sentence2"],
        how="inner"
    ).shape[0]
)

Обратных пар: 317

In [66]:
train_full["pair_key"] = train_full.apply(
    lambda x: tuple(sorted([x["sentence1"], x["sentence2"]])),
    axis=1
)

In [67]:
train_full = train_full.drop_duplicates(
    subset=["pair_key"]
).reset_index(drop=True)

train_full = train_full.drop(columns=["pair_key"])

In [68]:
print("Размер:", train_full.shape)
print("Дубликаты:", train_full[["sentence1", "sentence2"]].duplicated().sum())

Размер: (11772, 3)
Дубликаты: 0

In [69]:
print(train_full.shape)
print(train_full["label"].value_counts())
print(train_full["label"].value_counts(normalize=True))

(11772, 3)
label
0    7166
1    4606
Name: count, dtype: int64
label
0    0.608733
1    0.391267
Name: proportion, dtype: float64

## Splitting dataset

In [70]:
from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(
    train_full,
    test_size=0.15,
    random_state=42,
    stratify=train_full["label"]
)

print("train:", train_df.shape)
print("val:", val_df.shape)

print("\nTrain:")
print(train_df["label"].value_counts())

print("\nValidation:")
print(val_df["label"].value_counts())

train: (10006, 3)
val: (1766, 3)

Train:
label
0    6091
1    3915
Name: count, dtype: int64

Validation:
label
0    1075
1     691
Name: count, dtype: int64

In [72]:
from pathlib import Path

processed_dir = Path("processed")
processed_dir.mkdir(parents=True, exist_ok=True)

train_df.to_csv(
    processed_dir / "train.csv",
    index=False
)

val_df.to_csv(
    processed_dir / "val.csv",
    index=False
)

paraphraser_test_bin.to_csv(
    processed_dir / "test_paraphraser.csv",
    index=False
)

rupaws_test.to_csv(
    processed_dir / "test_rupaws.csv",
    index=False
)

In [73]:
print("train_full:")
print(train_full["label"].value_counts().sort_index())

print("\ntrain:")
print(train_df["label"].value_counts().sort_index())

print("\nvalidation:")
print(val_df["label"].value_counts().sort_index())

train_full:
label
0    7166
1    4606
Name: count, dtype: int64

train:
label
0    6091
1    3915
Name: count, dtype: int64

validation:
label
0    1075
1     691
Name: count, dtype: int64